services:
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: ssms-nacos
    environment:
      MODE: standalone
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    networks:
      - ssms-network
    restart: on-failure

  redis:
    image: redis:7.0
    container_name: ssms-redis
    ports:
      - "6379:6379"
    networks:
      - ssms-network
    restart: on-failure

networks:
  ssms-network:
    driver: bridge
